parameters:
  - name: 'BEFORE_SCRIPT'
    type: 'string'
    default: ''

jobs:
  - job: 'report_sonarqube'
    displayName: 'report:sonarqube'
    container:
      image: 'sonarsource/sonar-scanner-cli:latest'
      options: '--user root' # TODO: workaround for Azure DevOps error
    variables:
      GIT_DEPTH: '0'
      SONAR_USER_HOME: "$(Build.SourcesDirectory)/.sonar"
    steps:
      - task: DownloadPipelineArtifact@2
        displayName: 'Download Coverage File'
        inputs:
          artifactName: 'coverage'
          targetPath: '$(Build.SourcesDirectory)'
      - task: 'Cache@2'
        inputs:
          key: "$(Agent.JobName)"
          path: '.sonar/cache'
      - script: ${{ parameters.BEFORE_SCRIPT }}
      - script: sonar-scanner
